OUTPUT_DIR: ./outputs/phys
DATA_ROOT: 'data/simb/'
DATASET_ABS: 'SimB'
SOLVER:
  BASE_LR: 1.0e-3  # single GPU LR
  WEIGHT_DECAY: 1.0e-6
  SCHEDULER: 'cosine'
  MAX_ITERS: 20000000
  WARMUP_ITERS: 40000
  VAL_INTERVAL: 1000000
  BATCH_SIZE: 200 # single GPU Batch Size
INPUT:
  PRELOAD_TO_MEMORY: True
RPIN:
  BACKBONE: 'hourglass_S_bn'
  ARCH: 'rpcin'
  VE_FEAT_DIM: 64
  IN_FEAT_DIM: 64
  # prediction setting:
  INPUT_SIZE: 4
  PRED_SIZE_TRAIN: 20
  PRED_SIZE_TEST: 40
  # input setting:
  INPUT_HEIGHT: 64
  INPUT_WIDTH: 64
  MAX_NUM_OBJS: 3
  # data augmentation
  HORIZONTAL_FLIP: True
  VERTICAL_FLIP: True
  # loss weight
  POSITION_LOSS_WEIGHT: 1
  # ----- RoIPooling Setting
  ROI_POOL_SIZE: 3
  # ----- mask prediction
  MASK_LOSS_WEIGHT: 0.0
  # ----- Architecture
  N_EXTRA_ROI_F: 2
  N_EXTRA_PRED_F: 0
  N_EXTRA_SELFD_F: 0
  N_EXTRA_RELD_F: 0
  N_EXTRA_AFFECTOR_F: 0
  N_EXTRA_AGGREGATOR_F: 0
  # IMAGE_EXT: '.npy' # no need to use this