OUTPUT_DIR: ./outputs/phys
DATA_ROOT: 'data/ss/'
DATASET_ABS: 'SS'
SOLVER:
  BASE_LR: 2.0e-4  # single GPU LR
  WEIGHT_DECAY: 0.0
  SCHEDULER: 'cosine'
  MAX_ITERS: 1000000
  WARMUP_ITERS: 40000
  VAL_INTERVAL: 100000
  BATCH_SIZE: 20 # single GPU Batch Size
INPUT:
  IMAGE_MEAN: [105.34886558, 110.74936866, 105.03055784]
  IMAGE_STD: [73.17451869, 76.58094774, 75.4099835]
  PRELOAD_TO_MEMORY: False
RPIN:
  BACKBONE: 'hourglass_bn'
  ARCH: 'rpcin_vae'
  VE_FEAT_DIM: 256
  IN_FEAT_DIM: 256
  # prediction setting:
  INPUT_SIZE: 1
  PRED_SIZE_TRAIN: 15
  PRED_SIZE_TEST: 30
  # input setting:
  INPUT_HEIGHT: 224
  INPUT_WIDTH: 224
  MAX_NUM_OBJS: 3
  # data augmentation
  HORIZONTAL_FLIP: True
  VERTICAL_FLIP: False
  # loss weight
  POSITION_LOSS_WEIGHT: 1
  # ----- RoIPooling Setting
  ROI_POOL_SIZE: 7
  ROI_POOL_SAMPLE_R: 2
  # ----- mask prediction
  MASK_LOSS_WEIGHT: 0.001
  MASK_SIZE: 28
  # ----- Architecture
  N_EXTRA_ROI_F: 2
  N_EXTRA_PRED_F: 0
  N_EXTRA_SELFD_F: 0
  N_EXTRA_RELD_F: 0
  N_EXTRA_AFFECTOR_F: 0
  N_EXTRA_AGGREGATOR_F: 0
  EXTRA_F_KERNEL: 3
  EXTRA_F_PADDING: 1
  VAE: True
  VAE_KL_LOSS_WEIGHT: 3e-5
